# Generated by Django 3.0 on 2019-12-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('fileName', models.CharField(max_length=200)),
                ('fileSHA256', models.CharField(max_length=128)),
                ('uploadedToFile', models.CharField(max_length=200)),
                ('IV', models.CharField(max_length=32)),
                ('fileSize', models.IntegerField()),
                ('expirationTime', models.CharField(max_length=10)),
            ],
        ),
    ]
