# Generated by Django 3.0 on 2019-12-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='urlFName',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
