# Generated by Django 3.0 on 2019-12-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_upload_urlfname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='urlFName',
            field=models.CharField(max_length=40),
        ),
    ]
