# Generated by Django 3.0 on 2019-12-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191217_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='salt',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
