# Generated by Django 3.0 on 2020-02-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_upload_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='urlFName',
        ),
        migrations.AddField(
            model_name='upload',
            name='fileUUID',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
